version: "3"
services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/usr/src/app
    command: sh -c "npm run dev"
    tty: true
    ports:
      # - 3000:3000
      - $FRONTEND_PORT:3000
  
  backend:
    container_name: fastapi
    tty: true
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    environment:
      TZ: "Asia/Tokyo"
      # MONGO_DATABASE_NAME: mongodb
      # MONGO_DATABASE_USER: root
      # MONGO_DATABASE_PASSWORD: password
      # MONGO_DATABASE_CONTAINER_NAME: mongo_db
      # MONGO_DATABASE_PORT: 27017
      MONGO_DATABASE_NAME: ${MONGO_DATABASE_NAME}
      MONGO_DATABASE_USER: ${MONGO_DATABASE_USER}
      MONGO_DATABASE_PASSWORD: ${MONGO_DATABASE_PASSWORD}
      MONGO_DATABASE_CONTAINER_NAME: ${MONGO_DATABASE_CONTAINER_NAME}
      MONGO_DATABASE_PORT: $MONGO_DATABASE_PORT
    ports:
      #- 8888:8888
      - $BACKEND_PORT:8888
    depends_on:
      - mongo

  mongo:
    container_name: mongo_db
    image: mongo:4.0
    restart: always
    volumes:
      - ./mongodb_data:/data/db
    environment:
      #MONGO_INITDB_ROOT_USERNAME: root
      #MONGO_INITDB_ROOT_PASSWORD: password
      TZ: "Asia/Tokyo"
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      #- 27017:27017
      - $MONGO_PORT:27017
      # - ./configdb:/data/configdb 必要？とりあえず未作成

    
  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    environment:
      #ME_CONFIG_MONGODB_ADMINUSERNAME: root
      #ME_CONFIG_MONGODB_ADMINPASSWORD: password
      #ME_CONFIG_MONGODB_URL: mongodb://root:password@mongo:27017/
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${ME_CONFIG_MONGODB_ADMINUSERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${ME_CONFIG_MONGODB_ADMINPASSWORD}
      ME_CONFIG_MONGODB_URL: ${ME_CONFIG_MONGODB_URL}
    ports:
      #- 8081:8081
      - $MONGO_EXPRESS_PORT:8081
    depends_on:
      - mongo
      
volumes:
  mongodb_data: