version: "3"
services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/usr/src/app
    command: sh -c "npm run dev"
    tty: true
    ports:
      - $FRONTEND_PORT:3000

  backend:
    container_name: fastapi
    tty: true
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    environment:
      TZ: "Asia/Tokyo"
      MONGO_DATABASE_URL: ${MONGO_DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      FRONTEND_URL: ${FRONTEND_URL}
    ports:
      - $BACKEND_PORT:8888
    depends_on:
      - mongo 

  mongo:
    container_name: mongo_db
    image: mongo:4.0
    restart: always
    volumes:
      - ./mongodb_data:/data/db
    environment:
      TZ: "Asia/Tokyo"
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - $MONGO_PORT:27017

  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${ME_CONFIG_MONGODB_ADMINUSERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${ME_CONFIG_MONGODB_ADMINPASSWORD}
      ME_CONFIG_MONGODB_URL: ${ME_CONFIG_MONGODB_URL}
    ports:
      - $MONGO_EXPRESS_PORT:8081
    depends_on:
      - mongo

  redis:
    image: "redis:latest"
    ports: 
      - $REDIS_PORT:6379

  stripe-cli:
    image: stripe/stripe-cli
    container_name: stripe-cli
    environment:
      STRIPE_API_KEY: ${STRIPE_API_KEY}
      STRIPE_DEVICE_NAME: ${STRIPE_DEVICE_NAME}
    command: "listen --api-key ${STRIPE_API_KEY} --device-name ${STRIPE_DEVICE_NAME} --forward-to fastapi:8888/webhook/"

volumes:
  mongodb_data: